version: "3.8"

services:
  superset_sqlite:
    image: apache/superset:latest
    container_name: superset_sqlite
    hostname: superset_sqlite
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey
      - FLASK_ENV=production
    ports:
      - "8088:8088"
    volumes:
      - ./superset_home:/app/superset_home
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin --username admin --password admin --firstname Superset --lastname Admin --email admin@superset.com || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "
